### ISSUE TITLE
Atualizar diagrama de classes

### ISSUE THREAD

**Issue by menotti** [QuestIO42/Documentacao#27]
Contemplar ao menos as funcionalidades básicas de usuários, cursos e questões

**Comment by EnzoHirotani** [comment]
https://lucid.app/lucidchart/f5e6c5eb-463a-4fad-a00e-e6fe9bb9619d/edit?invitationId=inv_e14c10db-b853-4ef4-ab46-31e7446cf394&page=HWEp-vi-RSFO#

Adicionei as funções que foram criadas pelos back-ends e adicionei as funções, create, delete, get e update em todas as classes, menos nas intermediárias de muitos para muitos como o 'userSchoolroom'
